### ISSUE TITLE
не работает mirageSel

### ISSUE THREAD

**Issue by violetta-voloshina** [valnoc/Mirage#7]
при генерации частичного мока с помощью конструкции
//sourcery: miragePartial
и добавлении 
//sourcery: mirageSel=foo3str 
для функции func foo3(string: String, closure: @escaping Closure1)
в созданном моке было сгенерировано имя mock_foo3
При изменении //sourcery: miragePartial на //sourcery: mirageMock
и оставив //sourcery: mirageSel=foo3str без изменения, было сгенерировано имя mock_foo3str

**Comment by valnoc** [comment]
Спасибо за issue!

поскольку то проблема с генерацией, то перенесу issue в соседний проект Генерации
